name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn test
      - name: jacoco-badge-generator
        uses: cicirello/jacoco-badge-generator@v2.2.1
        with:
          generate-coverage-badge: true
          generate-branches-badge: true
      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
          echo `ls .github/badges`
      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Salavat R.Z.'
            git config --global user.email 'svart63@users.noreply.github.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2.2.1
        with:
          name: jacoco-report
          path: target/site/jacoco/
